name: webant
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #icon
  cupertino_icons: ^1.0.2

  #extra
  mask_text_input_formatter: ^2.0.0
  intl: ^0.17.0
  fluttertoast: ^8.0.7
  modal_bottom_sheet: ^2.0.0
  fancy_shimmer_image: ^2.0.0+1
  permission_handler: ^8.1.2
  custom_refresh_indicator: ^1.0.0
  infinite_scroll_pagination: ^3.1.0
  extended_nested_scroll_view: ^3.0.0

  #image
  photo_view: ^0.11.1
  camera: ^0.8.1+3
  image_picker: ^0.8.0+3
  flutter_svg: ^0.22.0

  #network
  dio: ^4.0.0

  #generator
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

  #state
  flutter_bloc: ^7.0.1

  #storage
  hive: ^2.0.4
  flutter_secure_storage: ^4.2.0

  #firebase
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ant.png
    - assets/Intersect.png
    -
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
          style: italic
    - family: GalleryIcons
      fonts:
        - asset: fonts/GalleryIcons.ttf

flutter_intl:
  main_locale: en
  enabled: true
